# @package _global_

data:
  train_files: ${oc.env:HOME}/data/medqa/train.parquet
  val_files: ${oc.env:HOME}/data/medqa/validation.parquet
  max_prompt_length: 1536
  max_response_length: 2048
  train_batch_size: 256
  filter_overlong_prompts: true

trainer:
  experiment_name: medqa
  minimize_entropy: True
